-- Add invoices table
create table if not exists public.invoices (
  id bigint generated by default as identity primary key,
  team_id bigint not null references public.teams(id) on delete cascade,
  stripe_invoice_id text not null unique,
  stripe_subscription_id text,
  amount_due bigint not null,
  amount_paid bigint not null default 0,
  currency text not null default 'usd',
  status text not null check (status in ('draft', 'open', 'paid', 'uncollectible', 'void')),
  billing_reason text,
  hosted_invoice_url text,
  invoice_pdf text,
  period_start timestamptz,
  period_end timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger set_invoices_updated_at
  before update on public.invoices
  for each row
  execute procedure public.set_updated_at();

create index if not exists invoices_team_id_idx on public.invoices (team_id);
create index if not exists invoices_stripe_invoice_id_idx on public.invoices (stripe_invoice_id);
create index if not exists invoices_status_idx on public.invoices (status);
create index if not exists invoices_created_at_idx on public.invoices (created_at desc);

-- Enable RLS
alter table public.invoices enable row level security;

-- RLS policies
create policy invoices_team_access on public.invoices
  for all
  using (public.current_app_user_role(team_id) in ('owner', 'admin'));

