-- Add user consents table for GDPR compliance
create table if not exists public.user_consents (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  consent_type text not null check (consent_type in ('cookies', 'marketing', 'analytics', 'necessary')),
  granted boolean not null default true,
  ip_address text,
  user_agent text,
  granted_at timestamptz not null default now(),
  revoked_at timestamptz,
  constraint user_consents_unique unique(user_id, consent_type)
);

create index if not exists user_consents_user_id_idx on public.user_consents (user_id);
create index if not exists user_consents_type_idx on public.user_consents (consent_type);

-- Enable RLS
alter table public.user_consents enable row level security;

-- RLS policies
create policy user_consents_self_access on public.user_consents
  for all
  using (user_id = public.current_app_user_id());

