create table if not exists public.function_logs (
  id bigint generated by default as identity primary key,
  function_name text not null,
  task_name text not null,
  status text not null check (status in ('success', 'failure')),
  message text not null,
  metadata jsonb,
  triggered_by bigint references public.users (id) on delete set null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists function_logs_function_name_idx
  on public.function_logs (function_name);

create index if not exists function_logs_task_name_idx
  on public.function_logs (task_name);

create index if not exists function_logs_created_at_idx
  on public.function_logs (created_at desc);
