name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  checks: write

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: 2.54.10

      - name: Start Supabase containers
        run: supabase start --exclude gotrue,realtime,storage-api,imgproxy,kong,mailpit,postgrest,postgres-meta,studio,edge-runtime,logflare,vector,supavisor

      - name: Apply Supabase migrations
        run: supabase migration up --db-url postgresql://postgres:postgres@127.0.0.1:54322/postgres

      - name: Generate Supabase type definitions
        run: pnpm supabase:typegen

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck

      - name: Unit tests
        run: pnpm test:unit

      - name: Integration tests
        run: pnpm test:integration

      - name: E2E tests
        run: pnpm test:e2e

      - name: Build
        run: pnpm build

      - name: Stop Supabase containers
        if: always()
        run: supabase stop
