name: Secrets Rotation Reminder

on:
  schedule:
    # Run every 90 days at 9 AM UTC
    - cron: '0 9 */90 * *'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to rotate secrets for'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging
          - development

jobs:
  create-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create rotation reminder issue
        uses: actions/github-script@v7
        with:
          script: |
            const nextRotationDate = new Date();
            nextRotationDate.setDate(nextRotationDate.getDate() + 90);
            
            const issueTitle = `Secrets Rotation Reminder - ${nextRotationDate.toISOString().split('T')[0]}`;
            const environment = '${{ github.event.inputs.environment || 'production' }}';
            
            const issueBody = `## Next Secrets Rotation Due

**Date:** ${nextRotationDate.toISOString().split('T')[0]}
**Environment:** ${environment}

### Critical Secrets to Rotate
- [ ] \`AUTH_SECRET\` - Better Auth JWT signing secret
- [ ] \`STRIPE_WEBHOOK_SECRET\` - Stripe webhook endpoint verification
- [ ] \`POSTGRES_PASSWORD\` - Database password (if using custom PostgreSQL)

### Environment-Specific Secrets
- [ ] \`SUPABASE_SERVICE_ROLE_KEY\` - Supabase admin access
- [ ] \`STRIPE_SECRET_KEY\` - Stripe API secret key
- [ ] \`NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY\` - Stripe public key

### Rotation Procedure
1. **Generate new secrets** using the rotation script
2. **Update GitHub secrets** via CLI or web interface
3. **Update environment variables** in hosting platform
4. **Redeploy application** to apply changes
5. **Test authentication** and webhook endpoints
6. **Monitor application** for 24 hours
7. **Document rotation** in security logs

### Automated Script
Run the PowerShell script for automated secret generation:
\`\`\`bash
# Dry run first
./scripts/rotate-secrets.ps1 -Environment "${environment}" -DryRun

# Actual rotation
./scripts/rotate-secrets.ps1 -Environment "${environment}"
\`\`\`

### Verification Checklist
- [ ] Authentication works correctly
- [ ] Stripe webhooks are received
- [ ] Database connections are stable
- [ ] All API endpoints respond correctly
- [ ] Monitoring shows no errors
- [ ] User sessions are maintained

### Emergency Contacts
- **Development Team**: dev-team@company.com
- **Security Team**: security@company.com
- **Infrastructure Team**: infra@company.com

---
*This reminder was automatically created by GitHub Actions.*
*Last rotation: ${new Date().toISOString().split('T')[0]}*
*Next rotation: ${nextRotationDate.toISOString().split('T')[0]}*`;

            // Check if similar issue already exists
            const existingIssues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'security,maintenance'
            });

            const duplicateIssue = existingIssues.data.find(issue => 
              issue.title.includes('Secrets Rotation Reminder')
            );

            if (duplicateIssue) {
              console.log('Similar issue already exists:', duplicateIssue.html_url);
              return;
            }

            // Create new issue
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody,
              labels: ['security', 'maintenance', 'automated']
            });

            console.log('Created issue:', issue.data.html_url);

      - name: Notify team
        if: github.event_name == 'schedule'
        uses: actions/github-script@v7
        with:
          script: |
            // Send notification to team (customize based on your notification system)
            console.log('Secrets rotation reminder created for production environment');
            console.log('Next rotation due in 90 days');
